// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LDNWebsiteOfficiall.Models
{
    public partial class Menus
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? ParentMenu { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Icon { get; set; }
        public long? PagesId { get; set; }
        public long? IsMenuParent { get; set; }
        public bool? IsDeleted { get; set; }
    }
}