// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LDNWebsiteOfficiall.Models
{
    public partial class Projects
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Description { get; set; }
        public DateTime? StartDate { get; set; }
        public decimal? Total { get; set; }
        public string Address { get; set; }
        public string FileUpload { get; set; }
        public DateTime? CreateDate { get; set; }
        public long? TypeContructedId { get; set; }
        public string Image { get; set; }
        public long? StatusId { get; set; }
        public bool? IsDeleted { get; set; }
        public string ModifyBy { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}